const Map<String, String> arEG = {
  'chose_lang': 'اختر لغة',

  //personal screen
  "Login": "تسجيل الدخول",
  "Language": "اللغة",
  'Sign Out': 'تسجيل الخروج',
  "register": "التسجيل",
  'SAVE': "حفظ",

  //register screen
  'Female': 'انثى',
  'Male': 'ذكر',
  'I don\'t want to tell': 'لا اريد ان اصرح',
  'Name': 'الإسم',
  'Name is required': "الاسم مطلوب",
  'Email': 'البريد الإلكترونى',
  'Email is Required': 'البريد الالكتروني مطلوب',
  'Enter a valid email address': 'أدخل عنوان بريد إلكتروني صالح',
  'Password': 'كلمة المرور',
  'Password Required': 'كلمة المرور مطلوبة',
  'Password less than 6 character': "كلمة المرور أقل من 6 أحرف",
  'Forget Password?': 'نسيت كلمة المرور؟',
  '-OR-': 'او',
  'Sign Up': 'انشاء حساب',
  'Gender': 'النوع',
  'SIGN UP': 'انشاء حساب',

  //login screen
  'Sign In': 'تسجيل الدخول',
  'Login as a guest': 'تسجيل الدخول كا زائر',
  'Welcome,': 'مرحبا,',
  'Sign in to Continue': 'سجل دخول حتي تكمل',
  'Birthdate': 'تاريخ الميلاد',
  'Next': 'التالي',
  'User Nationality': "جنسية المستخدم",
  'Are you egyptian?': 'هل انت مصري؟',
  "No": 'لا',
  'Egyptian': 'مصري',

  'Giza': 'الجيزة',
  'Alexandria': 'الإسكندرية',
  'Dakahlia': 'الدقهلية',
  'Eastern': "الشرقية",
  'Menoufia': "المنوفية",
  'Qalyubia': 'القليوبية',
  'the lake': 'البحيرة',
  'western': 'الغربي',
  'Port Said': 'بورسعيد',
  'Damietta': 'دمياط',
  'Ismailia': 'الإسماعيلية',
  'Suez': 'السويس',
  'Kafr El-Sheikh': 'كفر الشيخ',
  'Fayoum': "الفيوم",
  'Bani Sweif': "بني سويف",
  'subtracted': "مطروح",
  'North Sinai': 'شمال سيناء',
  'South of Sinaa': 'جنوب سيناء',
  'Minya': 'المنيا',
  'Asyut': "أسيوط",
  'Sohag': "سوهاج",
  'Qena': 'قنا',
  'The Red Sea': 'البحر الأحمر',
  'the shortest': 'الاقصر',
  'Aswan': "أسوان",
  'oases': "واحات",
  'the new Valley': 'الوادي الجديد',

  'cultural tourism': ' سياحة ثقافية ',
  'Medical tourism': 'سياحة علاجية',
  'Religious Tourism': 'سياحة دينية',
  'Adventure tourism': 'سياحة المغامرات',
  'rural tourism': 'سياحة ريفية',
  'Heritage tourism': 'سياحة تراثية',
  'Sports tourism': 'سياحة رياضية',
  'Educational tourism': 'سياحة تعليمية',

  'Governorates': 'المحافظات',
  'Tourism Type': 'نوع السياحة',
  'Home': 'الصفحة الرئيسية',
  'Favorite': 'مفضل',
  'Events': "أحداث",
  "Hello!": "مرحبًا!",
  "Find Your Place": "اعثر على مكانك",
  "Most Popular": "الأكثر شهرة",
  'Best Visits': "أفضل الزيارات",
  'Reviews': "التعليقات",
  'Dark Mode': "الوضع الليلي",
  'Light Mode': "الوضع النهاري",
  'LOGOUT': 'تسجيل خروج',
  'Edit Profile': 'تعديل الملف الشخصي',

  'Enter your email address': "أدخل عنوان البريد الإلكتروني",
  'Verify': "تحقق",
  'Old Password': "كلمة المرور القديمة",
  'Old password is requird': "كلمة المرور القديمة مطلوبة",
  'Old password less than 6 chars': "كلمة المرور القديمة أقل من 6 أحرف",
  'New Password': "كلمة المرور الجديدة",
  'New password is requird': "كلمة المرور الجديدة مطلوبة",
  'New password less than 6 chars': "كلمة المرور الجديدة أقل من 6 أحرف",
  'Re-New Password': "إعادة كلمة المرور الجديدة",
  'Re-new password is requird': "إعادة كلمة المرور الجديدة مطلوبة",
  'Passwords is not match': "كلمات المرور غير متطابقة",
  'Submit': 'إرسال',
  'Wrong': 'خطأ',
  'Something went wrong': "حدث خطأ ما",
  'Change Password': "تغيير كلمة المرور",
  'Change Password Successful': "تم تغيير كلمة المرور بنجاح",
  'Reset Password': "إعادة تعيين كلمة المرور",
  'Edit': 'تعديل',
  'Edit Successful': "تم التعديل بنجاح",
  'Login Successful': "تم تسجيل الدخول بنجاح",
  'Reset Password Successful': "تم إعادة تعيين كلمة المرور بنجاح",
  'Logout': "تسجيل الخروج",
  'Logout Successful': "تم تسجيل الخروج بنجاح",
  'Password reset OTP sent to your email':
      "إعادة تعيين كلمة المرور OTP المرسلة إلى بريدك الإلكتروني",
  'Signup Successful': 'تم انشاء الحساب بنجاح',
};
