const Map<String, String> arEG = {
  'chose_lang': 'اختر لغة',

  //personal screen
  "Login": "تسجيل الدخول",
  "Language": "اللغة",
  'Sign Out': 'تسجيل الخروج',
  "register": "التسجيل",
  'SAVE': "حفظ",

  //register screen
  'Female': 'انثى',
  'Male': 'ذكر',
  'I don\'t want to tell': 'لا اريد ان اصرح',
  'Name': 'الإسم',
  'Name is required': "الاسم مطلوب",
  'Email': 'البريد الإلكترونى',
  'Email is Required': 'البريد الالكتروني مطلوب',
  'Enter a valid email address': 'أدخل عنوان بريد إلكتروني صالح',
  'Password': 'كلمة المرور',
  'Password Required': 'كلمة المرور مطلوبة',
  'Password less than 6 character': "كلمة المرور أقل من 6 أحرف",
  'Forget Password?': 'نسيت كلمة المرور؟',
  '-OR-': 'او',
  'Sign Up': 'انشاء حساب',
  'Gender': 'النوع',
  'SIGN UP': 'انشاء حساب',

  //login screen
  'Sign In': 'تسجيل الدخول',
  'Login as a guest': 'تسجيل الدخول كا زائر',
  'Welcome,': 'مرحبا,',
  'Sign in to Continue': 'سجل دخول حتي تكمل',
  'Birthdate': 'تاريخ الميلاد',
  'Next': 'التالي',
  'User Nationality': "جنسية المستخدم",
  'Are you egyptian?': 'هل انت مصري؟',
  "No": 'لا',
  'Egyptian': 'مصري',

  'Giza': 'الجيزة',
  'Alexandria': 'الإسكندرية',
  'Dakahlia': 'الدقهلية',
  'Eastern': "الشرقية",
  'Menoufia': "المنوفية",
  'Qalyubia': 'القليوبية',
  'the lake': 'البحيرة',
  'western': 'الغربي',
  'Port Said': 'بورسعيد',
  'Damietta': 'دمياط',
  'Ismailia': 'الإسماعيلية',
  'Suez': 'السويس',
  'Kafr El-Sheikh': 'كفر الشيخ',
  'Fayoum': "الفيوم",
  'Bani Sweif': "بني سويف",
  'subtracted': "مطروح",
  'North Sinai': 'شمال سيناء',
  'South of Sinaa': 'جنوب سيناء',
  'Minya': 'المنيا',
  'Asyut': "أسيوط",
  'Sohag': "سوهاج",
  'Qena': 'قنا',
  'The Red Sea': 'البحر الأحمر',
  'the shortest': 'الاقصر',
  'Aswan': "أسوان",
  'oases': "واحات",
  'the new Valley': 'الوادي الجديد',

  'cultural tourism': ' سياحة ثقافية ',
  'Medical tourism': 'سياحة علاجية',
  'Religious Tourism': 'سياحة دينية',
  'Adventure tourism': 'سياحة المغامرات',
  'rural tourism': 'سياحة ريفية',
  'Heritage tourism': 'سياحة تراثية',
  'Sports tourism': 'سياحة رياضية',
  'Educational tourism': 'سياحة تعليمية',

  'Governorates': 'المحافظات',
  'Tourism Type': 'نوع السياحة'
};
