const Map<String, String> enUS = {
  'chose_lang': 'Choose Lang',
  "Login": "Login",
  'Sign Out': 'Sign Out',
  "register": "register",
  'SAVE': 'SAVE',

  //register screen
  'Female': 'Female',
  'Male': 'Male',
  'I don\'t want to tell': 'I don\'t want to tell',
  'Name': 'Name',
  'Name is required': 'Name is required',
  'Email': 'Email',
  'Email is Required': 'Email is Required',
  'Enter a valid email address': 'Enter a valid email address',
  'Password': 'Password',
  'Password Required': 'Password Required',
  'Password less than 6 character': 'Password less than 6 character',
  'Forget Password?': 'Forget Password?',
  '-OR-': '-Or-',
  'Sign Up': 'Sign Up',
  'Gender': 'GENDER',
  'SIGN UP': 'SIGN UP',

  //login screen
  'Sign In': 'Sign In',
  'Login as a guest': 'Login as a guest',
  'Welcome,': 'Welcome,',
  'Sign in to Continue': 'Sign in to Continue',
  'Birthdate': 'Birthdate',
  'Next': 'Next',
  'User Nationality': 'User Nationality',
  'Are you egyptian?': 'Are you egyptian?',
  "No": 'No',
  'Egyptian': 'Egyptian',
  'Giza': 'Giza',
  'Alexandria': 'Alexandria',
  'Dakahlia': 'Dakahlia',
  'Eastern': 'Eastern',
  'Menoufia': 'Menoufia',
  'Qalyubia': 'Qalyubia',
  'the lake': 'Al Bhera',
  'western': 'Al ghrbia',
  'Port Said': 'Port Said',
  'Damietta': 'Damietta',
  'Ismailia': 'Ismailia',
  'Suez': 'Suez',
  'Kafr El-Sheikh': 'Kafr El-Sheikh',
  'Fayoum': 'Fayoum',
  'Bani Sweif': 'Bani Sweif',
  'subtracted': 'Matroh',
  'North Sinai': 'North Sinai',
  'South of Sinaa': 'South of Sinaa',
  'Minya': 'Minya',
  'Asyut': 'Asyut',
  'Sohag': "سوهاج",
  'Qena': 'Qena',
  'The Red Sea': 'The Red Sea',
  'the shortest': 'Al Axor',
  'Aswan': 'Aswan',
  'oases': 'Wahat',
  'the new Valley': 'the new Valley',

  'cultural tourism': 'cultural tourism',
  'Medical tourism': 'Medical tourism',
  'Religious Tourism': 'Religious Tourism',
  'Adventure tourism': 'Adventure tourism',
  'rural tourism': 'rural tourism',
  'Heritage tourism': 'Heritage tourism',
  'Sports tourism': 'Sports tourism',
  'Educational tourism': 'Educational tourism',

  'Governorates': 'Governorates',
  'Tourism Type': 'Tourism Type',
  'Home': 'Home',
  'Favorite': 'Favorite',
  'Events': 'Events',
  "Hello!": "Hello!",
  "Find Your Place": "Find Your Place",
  "Most Popular": "Most Popular",
  'Best Visits': 'Best Visits',
  'Reviews': 'Reviews',
  'Dark Mode': 'Dark Mode',
  'Light Mode': 'Light Mode',
  'LOGOUT': 'LOGOUT',
  'Edit Profile': 'Edit Profile',

  'Enter your email address': 'Enter your email address',
  'Verify': 'Verify',
  'Old Password': 'Old Password',
  'Old password is requird': 'Old password is requird',
  'Old password less than 6 chars': 'Old password less than 6 chars',
  'New Password': 'New Password',
  'New password is requird': 'New password is requird',
  'New password less than 6 chars': 'New password less than 6 chars',
  'Re-New Password': 'Re-New Password',
  'Re-new password is requird': 'Re-new password is requird',
  'Passwords is not match': 'Passwords is not match',
  'Submit': 'Submit',
  'Wrong': 'Wrong',
  'Something went wrong': 'Something went wrong',
  'Change Password': 'Change Password',
  'Change Password Successful': 'Change Password Successful',
  'Reset Password': 'Reset Password',
  'Edit': 'Edit',
  'Edit Successful': 'Edit Successful',

  'Login Successful': 'Login Successful',
  'Reset Password Successful': 'Reset Password Successful',
  'Logout': 'Logout',
  'Logout Successful': 'Logout Successful',
  'Password reset OTP sent to your email':
      'Password reset OTP sent to your email',
  'Signup Successful': 'Signup Successful',
};
